    AWSTemplateFormatVersion: '2010-09-09'
    Description: 'DevSecOps - Reusable VPC w/ Public/Private Subnets, Internet Gateway, and Route Tables'

    Parameters:
        EnvironmentName:
        Type: String
        Description: Environment Name (i.e 1st tier, 2nd tier, 3rd tier)
        AllowedValues:
            - first
            - second
            - third
        Default: test

    ProjectName:
        Type: 'Cyber Byte'
        Description: 'DevSecOps'
        MinLength: 1
        MaxLength: 32

    VpcCidr:
        Type: String
        Description: CIDR block for VPC
        Default: 10.0.0.0/16
        AllowedPattern: '^(\d{1,3}\.){3}\d{1,3}/\d{1,2}$'

    PublicSubnetCidr:
        Type: String
        Description: CIDR block for public subnet
        Default: 10.0.1.0/24
        AllowedPattern: '^(\d{1,3}\.){3}\d{1,3}/\d{1,2}$'

    PrivateSubnetCidr:
        Type: String
        Description: CIDR block for public subnet
        Default: 10.0.2.0/24
        AllowedPattern: '^(\d{1,3}\.){3}\d{1,3}/\d{1,2}$'

    EnableFlowLogs:
        Type: String
        Description: Enable VPC Flow Logs for security monitoring
        AllowedValues:
            - 'true'
            - 'false'
        Default: 'true'


MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
    InstanceType: t3.micro
    KeyName: !Ref KeyName
    ImageId: !Ref LatestAmiId
    SubnetId: !Ref PublicSubnet
    SecurityGroupIds:
        - !Ref MySecurityGroup
        Tags:
            - Key: Name
                Value: MyEC2Instance
    UserData:
        Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            yum install -y httpd
            systemctl start httpd
            systemctl enable httpd
            echo "<h1>Welcome to your DevSecOps EC2 Instance via CloudFormation</h1>" > /var/www/html/index.html
